### ISSUE TITLE
FunctionSymbol`3 arguments

### ISSUE THREAD

**Issue by LieselThuriot** [terrajobst/nquery-vnext#13]
Hi,

It seems like FunctionSymbol\`3 uses the wrong argument type for parameter 3. I'd expect it to use `T3` rather than `T2`. 

I'll creat a pull request for this. If you want, I can alter my pull request to include a T4 template to auto generate these.

Kind regards,
Steven

**Comment by dallmair** [comment]
Good catch!

**Comment by terrajobst** [comment]
Fixed with #14.
